#!/bin/bash

# Remove previous log file if it exists
rm -f "time.txt"


for file in testers/*.1maps; do
    echo -e "\n\n\nProcessing $file" | tee -a "time.txt"

    { time ./navigate_p1 "$file"; } 2>&1 | tee -a "time.txt"

    # Define expected and output file names
    output_file="${file%.1maps}.sol1maps"
    expected_file="${file%.1maps}.QUERY"

    # Check if .sol1maps was generated by navigate
    if [ ! -f "$output_file" ]; then
        echo "Error: $output_file was not generated by navigate." | tee -a "time.txt"
        continue
    fi

    # Compare .sol1maps with .query
    if [ -f "$expected_file" ]; then
        diff "$output_file" "$expected_file" > /dev/null
        if [ $? -eq 0 ]; then
            echo "You did it, the files match!" | tee -a "time.txt"
        else
            echo "You're close, but there's a difference in the files." | tee -a "time.txt"
        fi
    else
        echo "Warning: Expected file $expected_file not found." | tee -a "time.txt"
    fi
done